# Site settings
title: Mr. Argote's Wares
email: mister.argote@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Plenty of goodies.
  Some worksheets, mostly links out.
  Share. Come back. Follow.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://mr.argote.org" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: MrArgote
github_username:  MrArgote

permalink: pretty

collections:
  worksheets:
    output: true
  tools:
    output: true
  shopping:
    output: true

defaults:
  -
    scope:
      type: "worksheets"
    values:
      layout: "printout"

# Build settings
markdown: kramdown
theme: minima
# plugins:
#  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
